### ISSUE TITLE
[ITensors] [BUG] Apply chain rule - Bug when applying the function apply more than once

### ISSUE THREAD

**Issue by danielalcalde** [ITensor/ITensors.jl#979] opened 2022-09-22 15:45 UTC
**Description of bug**
If the function apply is applied more than once the gradient is incorrect.
The error probably originates in:
src/ITensorChainRules/mps/abstractmps.jl

This is an issue when you want to apply operations that can not be formulated as gates in between applies.

<details><summary>Minimal runnable code</summary><p>

```julia
using PastaQ
using ITensors
using Zygote

N = 1
hilbert = siteinds("Qubit", N)

os = OpSum()
os += -1, "Y", 1
H = MPO(os, hilbert)

ψs = productstate(hilbert, fill(0, N))

function evolve(ψs, θ)
    g = gate("Rx", siteind(ψs, 1), (θ=θ[1]))
    
    g2 = gate("Rx", siteind(ψs, 1), (θ=θ[2]))
    ψ = apply([g, g2], ψs)
    return ψ
end

function evolve2(ρs, θ)
    g = gate("Rx", siteind(ψs, 1), (θ=θ[1]))
    g2 = gate("Rx", siteind(ψs, 1), (θ=θ[2]))
    
    ψ = apply([g], ψs)
    ψ = apply([g2], ψ)
    return ψ
end

function loss(θ)
    Uψ = evolve(ψs, θ)
    return real(inner(Uψ', H, Uψ))
end

function loss2(θ)
    Uψ = evolve2(ψs, θ)
    return real(inner(Uψ', H, Uψ))
end
θ = [0.6, 0.4]

println(loss(θ))
#0.8414709848078965

println(loss2(θ))
#0.8414709848078965

loss_grad = gradient(loss, θ)
println(loss_grad)
#([0.5403023058681398, 0.5403023058681398],)

loss_grad = gradient(loss2, θ)
println(loss_grad)
#([0.6967067093471655, 0.5403023058681398],) wrong gradient


```
</p></details>

**Expected output or behavior**

I expect both gradients to be the same.

**Actual output or behavior**

The gradient of the first parameter is wrong if the applies are executed after each other.

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cascadelake)
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
[9136182c] ITensors v0.3.19
```

**Comment by mtfishman** [comment] 2022-09-22 15:50
Hi, thanks for the report. I noticed that as well (#924), this is a good reminder to investigate it some more. I'll close this since it is a duplicate of #924.

**Closed by mtfishman** 2022-09-22 15:50 UTC
Labels: bug, ITensors
