### ISSUE TITLE
Possible Mismatch in Quantum Number block description

### ISSUE THREAD

**Issue by vipasu** [ITensor/ITensors.jl#240] opened 2020-03-26 04:07 UTC
Hi,

I'm testing out some of the QN conserving features and think I may have stumbled across a bug. The setup is using dmrg for finding the ground state in the m_z = 0 and m_z = 1 sector for the XXZ hamiltonian. Here is what I think is a roughly minimal code example to demonstrate what I'm finding.

```julia
using ITensors 
function xxzMPO(sites,
                J::Float64,
                Delta::Float64)
  # Input operator terms which define a Hamiltonian
  N = length(sites)
  ampo = AutoMPO()
  for j=1:N-1
    add!(ampo,4 * J/2.,"S+",j,"S-",j+1)
    add!(ampo,4 * J/2.,"S-",j,"S+",j+1)
    add!(ampo,4 * Delta, "Sz",j, "Sz",j+1)
  end
    add!(ampo,4 * J/2.,"S+",N,"S-",1)
    add!(ampo,4 * J/2.,"S-",N,"S+",1)
    add!(ampo,4 * Delta, "Sz",N, "Sz",1)

  # Convert these terms to an MPO tensor network
  return toMPO(ampo,sites)
end

function xxz_excited_state(N)
    sites = siteinds("S=1/2",N, conserve_qns=true)
    H_xxz = xxzMPO(sites, 1., .5);
    
    # sweep params
    sweeps = Sweeps(10)
    maxdim!(sweeps, 10,20,100,100,200, 500, 1000, 2000)
    cutoff!(sweeps, 1E-15)
    
    # Initialize ground state with total spin 0
    init_state = [isodd(n) ? "Up" : "Dn" for n=1:N]
    psi0 = productMPS(sites,init_state)
    energy, psi_0 = dmrg(H_xxz,psi0, sweeps,quiet=true)
    
    # initalize first ground state with total spin 1 
    init_state2 = copy(init_state)
    init_state2[end] = "Up"
    psi1 = productMPS(sites, init_state2)
    energy1, psi_1 = dmrg(H_xxz, psi1, sweeps, quiet=true)
    
    return psi_0, psi_1
end

function get_ket(M, pos)
    orthogonalize!(M, pos)
    ket = M[1]
    for i=2:pos
        ket *= M[i]
    end
    return ket
end

function extract_vectors(psi, b::Int64)

    ket = get_ket(psi, b)
    svd_result = svd(ket,tuple([ket.inds[i] for i = 1:b]...,), full=true, cutoff=1e-30)
    S = svd_result.S
    eigen_vals = S.store.^2
    return svd_result.U, eigen_vals
end

function printblocks(psi)
    num_blocks = dim(psi.inds.inds[end])
    for i=1:num_blocks
        println(block(psi, i))
    end
end

N = 8
ground, excited = xxz_excited_state(N)
ground_A, ground_spec = extract_vectors(ground, N÷2)
excited_A, excited_spec = extract_vectors(excited, N÷2)

println(excited_A.inds.inds[end]) # prints the link information
printblocks(excited_A)
```

The link information indicates that there are 10 relevant vectors with certain quantum numbers, while the block information seems to have a slightly different count for the quantum numbers.

**Comment by vipasu** [comment] 2020-03-26 04:20
Tangentially related, I ran into the problem due to #220. This might be moot since it sounds like eventually the backend will get switched back to QR. However, as of now (with an installation of ITensor on Monday), I wasn't able to run `orthogonalize` at sites other than the midpoint and the end. My installation still tries to call QR instead of SVD.

This was strange for two reasons. Calling it at other sites led to the methoderror, but I don't see how the types could be any different by passing in a different integer. The other strange occurrence was that after orthogonalizing at the end, calling orthogonalize at the midpoint gave a methoderror.

In code (continuing from above)
```julia
orthogonalize!(ground, 3)  # results in error
orthogonalize!(ground, 4)  # no error
orthogonalize!(ground, 8)  # no error
orthogonalize!(ground, 4)  # results in error
```

Again, this might just go away once QR is implemented, or possibly if I update my ITensor installation(?) to have the SVD method called, but I figured it wouldn't hurt to share this information.

**Comment by orialb** [comment] 2020-04-03 13:35
I'm using the latest master version (commit 4750566) and I also see a problem with `orthogonalize!`. with the function definition above and running:
```
N = 8
ground, excited = xxz_excited_state(N)
orthogonalize!(ground, 4)  # no error
orthogonalize!(ground, 8)  # no error
orthogonalize!(ground, 4)  # results in error
```

I get 
```
ERROR: MethodError: no method matching qr(::Tensor{Float64,2,BlockSparse{Float64,Array{Float64,1},2},IndexSet{2,Index{
Array{Pair{QN,Int64},1}}}}, ::Tuple{Int64}, ::Tuple{Int64})
Closest candidates are:
  qr(::Tensor{#s60,N,StoreT,IndsT} where StoreT<:Dense where #s60<:Number, ::Tuple{Vararg{Int64,NL}}, ::Tuple{Vararg{I
nt64,NR}}; kwargs...) where {N, IndsT, NL, NR} at /Users/oria/src/ITensors.jl/src/Tensors/dense.jl:662
  qr(::AbstractArray{T,2}, ::Any) where T at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib
/v1.3/LinearAlgebra/src/qr.jl:363
  qr(::ITensor, ::Any...; kwargs...) at /Users/oria/src/ITensors.jl/src/decomp.jl:9
  ...
Stacktrace:
 [1] #qr#165(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(qr), ::ITensor{2}, ::Ind
exSet{1,Index{Array{Pair{QN,Int64},1}}}) at /Users/USER/src/ITensors.jl/src/decomp.jl:13
 [2] qr(::ITensor{2}, ::IndexSet{1,Index{Array{Pair{QN,Int64},1}}}) at /Users/oria/src/ITensors.jl/src/decomp.jl:9
 [3] #orthogonalize!#226(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(orthogonaliz
e!), ::MPS, ::Int64) at /Users/USER/src/ITensors.jl/src/mps/mpo.jl:554
 [4] orthogonalize!(::MPS, ::Int64) at /Users/USER/src/ITensors.jl/src/mps/mpo.jl:530
 [5] top-level scope at REPL[12]:1
```

Maybe it's better to open a new issue for this as it seems unrelated to the original issue ?

**Comment by orialb** [comment] 2020-04-03 13:39
Regarding your original issue, I am not really familiar with the block sparse tensor code and I'm not really sure what is the issue you are seeing, but I think one problem is that you are not printing all the blocks in `printblocks`. Maybe try to use `num_blocks = nnzblocks(psi)` (but again this is just a guess from my side).

**Comment by mtfishman** [comment] 2020-04-03 19:34
The `orthogonalize!` issue should be fixed by #254.

**Comment by orialb** [comment] 2020-04-03 19:37
Thanks Matt! Was about to comment that this is not urgent for me, I just tried to reproduce this as I might be using QNs soon and I was curious about this issue. But I guess its too late for that :) .

**Comment by vipasu** [comment] 2020-04-05 22:53
Yes thanks for the quick fix on orthogonalize! I am also not urgently looking for a fix, was just looking to help report things that might not have been obvious to find.

Please excuse my limited understanding of condensed matter.
With that said, the call to `dim(psi.inds.inds[end])` was to get the link information, which I thought would tell me about the QNs on the left side of a Schmidt Decomposition. For a state initialized to have total spin 1, I think the `nzblocks` correctly indicates that the left side can have blocks for all states except for -2 spin on the left side. 

I guess then my confusion is why the link information indicates that there are only 8 vectors that appear in the svd?![link_info](https://user-images.githubusercontent.com/1889966/78511901-30a0ee00-7755-11ea-8219-a42af98b6a65.png) 

I could very easily be misunderstanding something, so definitely let me know if this is not the correct interpretation for any of these quantities.

**Comment by mtfishman** [comment] 2020-04-06 16:01
I think I understand your confusion now. I realized that you attempted to use the svd with `full=true`. However, the ITensor `svd` function does not currently support the `full` keyword (we have not come across a compelling use case for doing a full svd so far, and I am not sure if it is well defined for block sparse tensors). Therefore, it is not guaranteed that you will get the maximum number of singular vectors/values that you might expect from the dimensions of the problem. In fact, you are coming across a case like that in your current example. I've written a script to try to illustrate what is going on:
```julia
N = 8
psi0, psi1 = xxz_excited_state(N)

# Get the site indices
sites = siteinds(psi0)

# Bond we are interested in
b = N÷2

orthogonalize!(psi0, b)
orthogonalize!(psi1, b)

println("""Show the link degrees of freedom
           at the cut we are interested in.
           Note that of the maximum number
           of states 2^b, not all are kept
           in psi1.""")
@show linkind(psi0, b)
@show dim(linkind(psi0, b))
println()
@show linkind(psi1, b)
@show dim(linkind(psi1, b))

println()
println("""Get the full wavefunction by 
        multiplying all of the tensors
        together (with the Julia function prod).""")
psi0_full = prod(store(psi0))
psi1_full = prod(store(psi1))

println()
println("svd the full wavefunction:")
println("""This reproduces what we see from
        the MPS (note that 16 states are
        not kept in psi1).""")
U0,S0,V0 = svd(psi0_full, sites[1:b]...; cutoff=0)
U1,S1,V1 = svd(psi1_full, sites[1:b]...; cutoff=0)

@show commonind(U0,S0)
@show dim(commonind(U0,S0))
@show commonind(U1,S1)
@show dim(commonind(U1,S1))

println()
println("""To understand why, we can look at
        the block structure by combining
        the indices.""")
CL,cL = combiner(sites[1:b]...)
CR,cR = combiner(sites[b+1:end]...)

println()
println("""Note that psi1_full has fewer blocks than 
        psi0_full. If you add up the minimum
        dimensions of the blocks, you can
        see they add up to 8, not 16""")
@show psi0_full*CL*CR
@show psi1_full*CL*CR
```
So because of the block structure of the excited state wavefunction compared to the ground state wavefunction, structurally not all of the states exist (in terms of the sparsity structure). For a case like that, a "full" svd may not make much sense.

**Comment by mtfishman** [comment] 2020-04-06 16:08
Also note that in the `svd` call above, if I remove `cutoff = 0` then I am hitting a bug in our svd function. I am fixing it now, just wanted to point it out in case you come across the same thing.

**Comment by vipasu** [comment] 2020-04-07 17:47
I see. Thanks for looking into it! Feel free to close.

**Closed** 2020-04-10 17:32 UTC
