### ISSUE TITLE
[ITensorGPU] [BUG] Adding complex and real ITensors on GPU

### ISSUE THREAD

**Issue by hjkqubit** [ITensor/ITensors.jl#1026] opened 2022-11-29 21:38 UTC
**Description of bug**

Adding complex (`ComplexF64`) and real (`Float64`) ITensors on GPU causes an error.

**Minimal code demonstrating the bug or unexpected behavior**

<details><summary>Minimal runnable code</summary><p>

```julia
using ITensors
using ITensorGPU

gpu = cu
i = Index(2)
A = cu(randomITensor(Float64, i))
B = cu(randomITensor(ComplexF64, i))
A + B
```
</p></details>

**Expected output or behavior**

We'd expect the code to run without raising an error.

**Actual output or behavior**

<details><summary>Output of minimal runnable code</summary><p>

```julia
ERROR: LoadError: GPU compilation of kernel broadcast_kernel(CUDA.CuKernelContext, CUDA.CuDeviceVector{Float64, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{1}, Tuple{Base.OneTo{Int64}}, ITensors.var"#286#287"{Base.Broadcast.Broadcasted{ITensors.ITensorStyle, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{ITensor, ITensor}}}, Tuple{Base.Broadcast.Extruded{CUDA.CuDeviceVector{Float64, 1}, Tuple{Bool}, Tuple{Int64}}, Base.Broadcast.Extruded{CUDA.CuDeviceVector{ComplexF64, 1}, Tuple{Bool}, Tuple{Int64}}}}, Int64) failed
KernelError: passing and using non-bitstype argument

Argument 4 to your kernel function is of type Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{1}, Tuple{Base.OneTo{Int64}}, ITensors.var"#286#287"{Base.Broadcast.Broadcasted{ITensors.ITensorStyle, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{ITensor, ITensor}}}, Tuple{Base.Broadcast.Extruded{CUDA.CuDeviceVector{Float64, 1}, Tuple{Bool}, Tuple{Int64}}, Base.Broadcast.Extruded{CUDA.CuDeviceVector{ComplexF64, 1}, Tuple{Bool}, Tuple{Int64}}}}, which is not isbits:
  .f is of type ITensors.var"#286#287"{Base.Broadcast.Broadcasted{ITensors.ITensorStyle, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{ITensor, ITensor}}} which is not isbits.
    .bc is of type Base.Broadcast.Broadcasted{ITensors.ITensorStyle, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{ITensor, ITensor}} which is not isbits.
      .args is of type Tuple{ITensor, ITensor} which is not isbits.
        .1 is of type ITensor which is not isbits.
          .tensor is of type NDTensors.Tensor which is not isbits.
            .storage is of type NDTensors.TensorStorage which is not isbits.
            .inds is of type Any which is not isbits.
        .2 is of type ITensor which is not isbits.
          .tensor is of type NDTensors.Tensor which is not isbits.
            .storage is of type NDTensors.TensorStorage which is not isbits.
            .inds is of type Any which is not isbits.


Stacktrace:
  [1] check_invocation(job::GPUCompiler.CompilerJob)
    @ GPUCompiler C:\Users\hjkqu\.julia\packages\GPUCompiler\I9fZc\src\validation.jl:66
  [2] macro expansion
    @ C:\Users\hjkqu\.julia\packages\GPUCompiler\I9fZc\src\driver.jl:326 [inlined]
  [3] macro expansion
    @ C:\Users\hjkqu\.julia\packages\TimerOutputs\LHjFw\src\TimerOutput.jl:253 [inlined]
  [4] macro expansion
    @ C:\Users\hjkqu\.julia\packages\GPUCompiler\I9fZc\src\driver.jl:325 [inlined]
  [5] emit_asm(job::GPUCompiler.CompilerJob, ir::LLVM.Module; strip::Bool, validate::Bool, format::LLVM.API.LLVMCodeGenFileType)
    @ GPUCompiler C:\Users\hjkqu\.julia\packages\GPUCompiler\I9fZc\src\utils.jl:64
  [6] cufunction_compile(job::GPUCompiler.CompilerJob)
    @ CUDA C:\Users\hjkqu\.julia\packages\CUDA\5jdFl\src\compiler\execution.jl:326
  [7] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link))
    @ GPUCompiler C:\Users\hjkqu\.julia\packages\GPUCompiler\I9fZc\src\cache.jl:90
  [8] cufunction(f::GPUArrays.var"#broadcast_kernel#17", tt::Type{Tuple{CUDA.CuKernelContext, CUDA.CuDeviceVector{Float64, 1}, Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{1}, Tuple{Base.OneTo{Int64}}, ITensors.var"#286#287"{Base.Broadcast.Broadcasted{ITensors.ITensorStyle, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{ITensor, ITensor}}}, Tuple{Base.Broadcast.Extruded{CUDA.CuDeviceVector{Float64, 1}, Tuple{Bool}, Tuple{Int64}}, Base.Broadcast.Extruded{CUDA.CuDeviceVector{ComplexF64, 1}, Tuple{Bool}, Tuple{Int64}}}}, Int64}}; name::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ CUDA C:\Users\hjkqu\.julia\packages\CUDA\5jdFl\src\compiler\execution.jl:297
  [9] cufunction
    @ C:\Users\hjkqu\.julia\packages\CUDA\5jdFl\src\compiler\execution.jl:291 [inlined]
 [10] macro expansion
    @ C:\Users\hjkqu\.julia\packages\CUDA\5jdFl\src\compiler\execution.jl:102 [inlined]
 [11] #launch_heuristic#282
    @ C:\Users\hjkqu\.julia\packages\CUDA\5jdFl\src\gpuarrays.jl:17 [inlined]
 [12] _copyto!
    @ C:\Users\hjkqu\.julia\packages\GPUArrays\fqD8z\src\host\broadcast.jl:63 [inlined]
 [13] materialize!(#unused#::CUDA.CuArrayStyle{1}, dest::Base.ReshapedArray{Float64, 1, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}, Tuple{}}, bc::Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{1}, Nothing, ITensors.var"#286#287"{Base.Broadcast.Broadcasted{ITensors.ITensorStyle, Tuple{Base.OneTo{Int64}}, typeof(+), Tuple{ITensor, ITensor}}}, Tuple{Base.ReshapedArray{Float64, 1, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}, Tuple{}}, Base.ReshapedArray{ComplexF64, 1, CUDA.CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}, Tuple{}}}})
    @ GPUArrays C:\Users\hjkqu\.julia\packages\GPUArrays\fqD8z\src\host\broadcast.jl:41
 [14] materialize!
    @ .\broadcast.jl:868 [inlined]
 [15] permutedims!!(R::NDTensors.DenseTensor{Float64, 1, Tuple{Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, T::NDTensors.DenseTensor{ComplexF64, 1, Tuple{Index{Int64}}, NDTensors.Dense{ComplexF64, CUDA.CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}}}, perm::Tuple{Int64}, f::Function)
    @ NDTensors C:\Users\hjkqu\.julia\packages\NDTensors\lTD8N\src\dense\dense.jl:430
 [16] _map!!(f::Function, R::NDTensors.DenseTensor{Float64, 1, Tuple{Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, T1::NDTensors.DenseTensor{Float64, 1, Tuple{Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, T2::NDTensors.DenseTensor{ComplexF64, 1, Tuple{Index{Int64}}, NDTensors.Dense{ComplexF64, CUDA.CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}}})
    @ ITensors C:\Users\hjkqu\.julia\packages\ITensors\5CAqA\src\itensor.jl:2609
 [17] map!(f::Function, R::ITensor, T1::ITensor, T2::ITensor)
    @ ITensors C:\Users\hjkqu\.julia\packages\ITensors\5CAqA\src\itensor.jl:2614
 [18] copyto!
    @ C:\Users\hjkqu\.julia\packages\ITensors\5CAqA\src\broadcast.jl:299 [inlined]
 [19] materialize!
    @ .\broadcast.jl:871 [inlined]
 [20] materialize!
    @ .\broadcast.jl:868 [inlined]
 [21] _add(A::NDTensors.DenseTensor{Float64, 1, Tuple{Index{Int64}}, NDTensors.Dense{Float64, CUDA.CuArray{Float64, 1, CUDA.Mem.DeviceBuffer}}}, B::NDTensors.DenseTensor{ComplexF64, 1, Tuple{Index{Int64}}, NDTensors.Dense{ComplexF64, CUDA.CuArray{ComplexF64, 1, CUDA.Mem.DeviceBuffer}}})
    @ ITensors C:\Users\hjkqu\.julia\packages\ITensors\5CAqA\src\itensor.jl:1836
 [22] +(A::ITensor, B::ITensor)
    @ ITensors C:\Users\hjkqu\.julia\packages\ITensors\5CAqA\src\itensor.jl:1844
 [23] top-level scope
    @ C:\Users\hjkqu\Documents\Code\AGP-MPO\test3.jl:31
in expression starting at C:\Users\hjkqu\Documents\Code\AGP-MPO\test3.jl:31
```
</p></details>

**Version information**

 - Output from `versioninfo()`:
```julia
julia> versioninfo()
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
OS: Windows (x86_64-w64-mingw32)
CPU: AMD Ryzen 9 4900HS with Radeon Graphics
WORD_SIZE: 64
LIBM: libopenlibm
LLVM: libLLVM-12.0.1 (ORCJIT, znver2)
```
 - Output from `using Pkg; Pkg.status("ITensors")`:
```julia
julia> using Pkg; Pkg.status("ITensors")
Status `C:\Users\hjkqu\.julia\environments\v1.7\Project.toml`
  [9136182c] ITensors v0.3.20
```

**Comment by kmp5VT** [comment] 2022-12-05 17:29
Hello @hjkqubit, I am currently working on the ITensors package to be able to utilize any kind of ITensor on GPU. As you know, ITensorsGPU uses a hardcoded NDTensors.Dense(CuTensor{Float64}) storage backend to the ITensorsGPU type.

**Comment by mtfishman** [comment] 2023-02-22 12:44
@kmp5VT @hjkqubit is this fixed now? I think the issue is in some conversion in the generic `permutedims!!` code, which has changed a bit at this point.

**Comment by kmp5VT** [comment] 2023-02-22 17:58
@mtfishman @hjkqubit This now works properly when you do `B + A` Because A is converted to a ComplexF64. But it does not work for `A + B` Because it tries to convert B to a Float64

**Comment by kmp5VT** [comment] 2023-02-23 21:36
@mtfishman @hjkqubit I believe that I have fixed this issue in this PR https://github.com/ITensor/ITensors.jl/pull/1075.

**Comment by kmp5VT** [comment] 2023-03-10 12:07
@hjkqubit this issue should be fixed now. Please open a new issue if you are experiencing any other problems. Thanks!

**Closed by kmp5VT** 2023-03-10 12:07 UTC
Labels: bug, ITensorGPU
