### ISSUE TITLE
Use Symbols for tags

### ISSUE THREAD

**Issue by MasonProtter** [ITensor/ITensors.jl#2] opened 2019-07-23 18:02 UTC
Is there any reason to use `String`s for tags instead of `Symbols`? 
```julia
Index(2, :m) 
```
feels much more julian to me than
```julia
Index(2, "m") 
```

**Comment by emstoudenmire** [comment] 2019-07-23 18:22
It's a good question. We didn't consider symbols very strongly, since we were mostly in a default mode of keeping a lot of our design decisions from C++ that we were happy with, especially when doing the same design in Julia was straightforward and didn't require a performance hit.

But as to whether we should use symbols for the Index tags, here are some reasons strings still seem like a better choice to me right now:
* we can pass multiple tags as a single string, using commas to separate the tags. So like "Site,X,n=1"
* string interpolation is sometimes very useful to combine with tags, so like `Index(4,"Site,n=$n")` in a scope where there is a variable called `n`
* strings and "..." notation are already familiar to users coming from other languages. It's been a big win for us in C++ to use a very friendly and common subset of C++, and so to not require our users to master more  C++ specific techniques like templates, iostreams syntax, std lib iterators, etc.

We did end up writing our own small-string mini library though. And that's a place where the Symbol type already may offer certain performance aspects we had to work to reproduce.

**Comment by mtfishman** [comment] 2019-07-23 18:31
I just noticed Miles' answer above but I can expand a bit on why Indices have sets of tags, not just a single tag. For example:

```julia
xy = Index(2, "x,y")
yz = Index(2, "y,z")
xz = Index(2, "x,z")
```

Index `xy` has the tags `"x"` and `"y"`, Index `yz` has tags `"y"` and `"z"`, etc.

This makes it easy to grab different subsets of indices, for example:

```julia
A = randomITensor(xy,yz,xz)

# Get subsets of indices:
ys = findinds(A, "y")   # Get a set of indices with the tag "y", i.e. (xy, yz)
xs = findinds(A, "x")   # Get a set of indices with the tag "x", i.e. (xy,xz)
```

These are operations that we use a lot in our algorithms (many times we want to treat a tensor as a map from one set of indices to another, so identifying a subset of indices is useful for doing that).

We could maybe use a tuple notation for a set of tags, like `(:x, :y)`, but I think `"x,y"` is a bit nicer and more compact. We have optimized creating and comparing tags and set of tags quite a lot, so we believe there shouldn't be too much overhead to using strings (internally TagSets are actually stored as an ordered fixed-size vector of small integers).

Cheers,
Matt

**Comment by MasonProtter** [comment] 2019-07-23 18:39
Fair enough, I guess I just get quite suspicious whenever I see strings in an api like this. It seems like an easy way to introduce bugs and sometimes produces confusing behaviour. I'd think that `Index(2, :x, :y)`, `Index(2, (:x, :y))` or `Index(2, :(x, y))` would be preferable since `ITensor` just needs to deal with a nice data structure instead of trying to correctly parse that data structure out of a string. 

Either way, this is not a big deal, I just thought I'd point out a place that this differs from typical julia APIs.

**Comment by mtfishman** [comment] 2019-07-23 18:57
Using a macro is an interesting suggestion, but that would mean that all functions using tags would need a macro to correctly parse the inputs, and tags are used all over in a variety of functions (not just Index construction).

I'll close this, but it is definitely a good point to raise and we could consider other APIs and data structures for tags/tagsets in the future.

**Closed by mtfishman** 2019-07-23 18:57 UTC
