### ISSUE TITLE
DMRG occasionally gives very wrong answer

### ISSUE THREAD

**Issue by sujay-kazi** [ITensor/ITensors.jl#234] opened 2020-03-24 06:24 UTC
I have found that DMRG occasionally gives a very wrong answer on a very simple Hamiltonian. I used the Hamiltonian H = -(sum from j = 1 to N)S_j^z (just a Pauli-z matrix on each particle, with no interactions between neighbors). The ground state energy is clearly -N, and usually the program gives this correctly, but the program will give an answer much lower than this (something like -1.5N to -3N) up to 20% of the time (for N = 5 to 20 it seems to be lower).

To show an example of this, I ran DMRG 100 separate times (all with different initializations, chosen using the command psi0 = randomMPS(sites)) for N = 100. Here is an example of what a correct run looked like for me:

Trial 2:
After sweep 1 energy=-84.934490501774 maxlinkdim=5 time=0.257
After sweep 2 energy=-95.364721763258 maxlinkdim=15 time=0.400
After sweep 3 energy=-99.349810066932 maxlinkdim=26 time=0.612
After sweep 4 energy=-99.958095815756 maxlinkdim=31 time=0.638
After sweep 5 energy=-99.994179503234 maxlinkdim=24 time=0.460
Final energy = -99.99417950323418
Expected energy = -100

And here is an example of what an incorrect run looked like for me:

Trial 3:
After sweep 1 energy=-84.296520611164 maxlinkdim=5 time=0.259
After sweep 2 energy=-92.686538471605 maxlinkdim=16 time=0.398
After sweep 3 energy=-96.351629915200 maxlinkdim=29 time=0.572
After sweep 4 energy=-98.323749683386 maxlinkdim=29 time=0.650
After sweep 5 energy=-240.380636427750 maxlinkdim=38 time=0.574
Final energy = -240.38063642775018
Expected energy = -100

One thing I've noticed is that sometimes the run goes haywire on an earlier sweep, and then somehow it magically gets fixed on the next sweep, such as here:

Trial 39:
After sweep 1 energy=-84.034964797986 maxlinkdim=5 time=0.260
After sweep 2 energy=-93.790455347323 maxlinkdim=17 time=0.406
After sweep 3 energy=-97.326033857518 maxlinkdim=31 time=0.664
After sweep 4 energy=-251.224945310846 maxlinkdim=38 time=0.905
After sweep 5 energy=-99.995652140835 maxlinkdim=27 time=0.639
Final energy = -99.99565214083535
Expected energy = -100

In fact, one thing I tried was to check for an "obviously wrong" answer and then run DMRG for an extra sweep if that was the case, and this always fixed the problem. Also, the choice of psi0 definitely has some role to play, because the DMRG algorithm doesn't have any randomness (I tried multiple runs with the same psi0 and got the exact same result every time).

Does someone know what might be causing this error? Any clarity would be greatly appreciated.

**Comment by mtfishman** [comment] 2020-03-24 15:03
Thanks for the report. That is a very strange bug, I am seeing the same thing. We will look into it (it is hard to guess what the problem might be without some debugging).

**Comment by emstoudenmire** [comment] 2020-03-24 15:18
Thanks for the report. A key question for us is: how did you make the Hamiltonian and what is the local Hilbert space of the site indices used? Did you use AutoMPO? Are the sites QN-conserving or not? And are they fermionic, bosonic, or spin sites? Thanks!

**Comment by emstoudenmire** [comment] 2020-03-24 15:18
Ideally if you could also post some minimal code that reproduces the error that would be very helpful too.

**Comment by mtfishman** [comment] 2020-03-24 18:19
Here is a minimal example:
```julia
using ITensors

let
  N = 4
  sites = siteinds("S=1/2",N)
  ampo = AutoMPO()
  for j=1:N
    ampo += (-2,"Sz",j)
  end
  H = MPO(ampo,sites)
  sweeps = Sweeps(10)
  maxdim!(sweeps, 10,20,100,100,200)
  cutoff!(sweeps, 1E-10)
  for i = 1:100
    psi0 = randomMPS(sites)
    energy, psi = dmrg(H,psi0, sweeps; quiet=true)
    println("Final energy = $energy")
    end
  end
end
```
You should see that instead of the expected energy of -4, occasionally the energy is much less.

It looks like this is a problem with davidson. I replaced the `davidson` call in dmrg with `eigsolve` from KrylovKit, and the problem goes away. Additionally, when I call both ITensor's `davidson` and KrylovKit's `eigsolve` back-to-back (with the same starting vector), there are steps of dmrg where `davidson` gets an eigenvalue that is way lower than expected, while `eigsolve` gets the correct energy of `-N`. 

I haven't looked into `davidson` to figure out what the problem is, but perhaps we should consider just using KrylovKit .

**Comment by sujay-kazi** [comment] 2020-03-24 18:30
Here is a minimal example. I used AutoMPO and bosonic sites. I believe my sites are not QN-conserving.

```
num_trials = 100
N = 10

ampo = AutoMPO()
for j=1:N
  add!(ampo,-1,"Sz",j)
end
H = MPO(ampo,sites)

for k=1:num_trials
  psi0 = randomMPS(sites)
  sweeps = Sweeps(5)
  maxdim!(sweeps, 10,20,100,100,200)
  cutoff!(sweeps, 1E-10)
  energy, psi = dmrg(H,psi0, sweeps)
  println("Final energy = $energy")
  println("Expected energy = $expected")
end
```

**Comment by mtfishman** [comment] 2020-03-24 19:32
@sujay-kazi, I believe this problem is fixed by the pull request #236. Could you try out the branch [replace_davidson](https://github.com/ITensor/ITensors.jl/tree/replace_davidson) and see if it helps?

**Comment by emstoudenmire** [comment] 2020-03-24 19:53
Glad we know the solution here. I'm not too surprised that KrylovKit has a better implementation, though a bit surprised our Davidson code broke on such a simple case. But we've been wanting to move to KrylovKit eventually anyway so now seems like an ideal time!

**Comment by mtfishman** [comment] 2020-03-24 20:26
It is surprising, possibly it is something simple like having the wrong stopping criteria (since the eigenvector is very trivial, since it is just a product state). Hopefully we will just be able to use KrylovKit and not have to support our own version.

**Closed** 2020-03-25 15:00 UTC
Labels: bug, dmrg
