### ISSUE TITLE
Excited states showing up in wrong order

### ISSUE THREAD

**Issue by sujay-kazi** [ITensor/ITensors.jl#311] opened 2020-04-21 19:31 UTC
I wrote the following code to compute many excited states on my favorite test model, the super-simple chain of N spins with just an Sz on each site:

```
# define parameters
N = 4
proj_weight = 15.0 # weight to add to projectors when computing excited states
excite_num = 15 # number of excited states to find (0 if just want ground state)

# define physical system and DMRG parameters
sites = siteinds("S=1/2",N) # Create N spin-1/2 (dimension 2) indices
ampo = AutoMPO()
for j = 1:N
  add!(ampo,-1,"Sz",j)
end
H = MPO(ampo,sites)
sweeps = Sweeps(5)
maxdim!(sweeps, 10,20,100,100,200)
cutoff!(sweeps, 1E-10)

# compute ground state
println("N = $N:")
psi0i = randomMPS(sites)
println("Computing ground state...")
E0, psi0 = dmrg(H, psi0i, sweeps; quiet=true)
println("Ground state: energy = $E0")

# run more iterations to find energies of excited states
energies = [E0]
states = [psi0]
for i = 1:excite_num
  println("Computing excited state $i...")
  psi_init = randomMPS(sites)
  E, psi = dmrg(H, states, psi_init, sweeps; quiet=true, weight=proj_weight)
  println("Excited state $i: energy = $E")
  push!(energies, E)
  push!(states, deepcopy(psi))
end
```

What we should see here is that the degeneracies are binomial coefficients, and that the energies should go from smallest to largest. In particular, for each integer r from 0 to N, there should be (N choose r) = N!/(r!(n-r)!) states with energy E(r) = r - N/2.

For example, if N = 4, then the ground state should have energy -2, excited states 1-4 should have energy -1, excited states 5-10 should have energy 0, excited states 11-14 should have energy 1, and excited state 15 should have energy 2. However, when I run my code, I see this:

```
N = 4:
Computing ground state...
Ground state: energy = -2.0
Computing excited state 1...
Excited state 1: energy = -1.0
Computing excited state 2...
Excited state 2: energy = -1.0000000000000002
Computing excited state 3...
Excited state 3: energy = -1.0
Computing excited state 4...
Excited state 4: energy = -1.2474185167353233e-30
Computing excited state 5...
Excited state 5: energy = -7.224168168988943e-31
Computing excited state 6...
Excited state 6: energy = -1.0
Computing excited state 7...
Excited state 7: energy = 3.5608274434719e-30
Computing excited state 8...
Excited state 8: energy = 1.0
Computing excited state 9...
Excited state 9: energy = 4.5604191449639797e-29
Computing excited state 10...
Excited state 10: energy = 1.5646452889519525e-10
Computing excited state 11...
Excited state 11: energy = 6.273845104730043e-13
Computing excited state 12...
Excited state 12: energy = 1.0
Computing excited state 13...
Excited state 13: energy = 1.0
Computing excited state 14...
Excited state 14: energy = 1.0
Computing excited state 15...
Excited state 15: energy = 2.0000000000000036
```

Notice that the degeneracies are correct--each energy shows up the correct number of times. However, they don't quite show up in the right order. For instance, we start getting energies of 0 before we have gotten all 4 of the states with energy -1.

As another example, I ran the above code but set N = 5 and excite_num = 40:

```
N = 5:
Computing ground state...
Ground state: energy = -2.5
Computing excited state 1...
Excited state 1: energy = -1.5
Computing excited state 2...
Excited state 2: energy = -1.5
Computing excited state 3...
Excited state 3: energy = -1.4999999999999996
Computing excited state 4...
Excited state 4: energy = -1.500000000000001
Computing excited state 5...
Excited state 5: energy = -0.5
Computing excited state 6...
Excited state 6: energy = -1.4999999999999996
Computing excited state 7...
Excited state 7: energy = -0.5
Computing excited state 8...
Excited state 8: energy = -0.5
Computing excited state 9...
Excited state 9: energy = -0.49999999999431033
Computing excited state 10...
Excited state 10: energy = -0.4999999999999999
Computing excited state 11...
Excited state 11: energy = -0.4999999999999991
Computing excited state 12...
Excited state 12: energy = 0.49999999999999994
Computing excited state 13...
Excited state 13: energy = -0.5000000000000003
Computing excited state 14...
Excited state 14: energy = -0.5
Computing excited state 15...
Excited state 15: energy = -0.49999999999999734
Computing excited state 16...
Excited state 16: energy = 0.5
Computing excited state 17...
Excited state 17: energy = 0.5
Computing excited state 18...
Excited state 18: energy = -0.5
Computing excited state 19...
Excited state 19: energy = 0.5
Computing excited state 20...
Excited state 20: energy = 0.500000000000027
Computing excited state 21...
Excited state 21: energy = 0.5000000000000001
Computing excited state 22...
Excited state 22: energy = 0.4999999999999998
Computing excited state 23...
Excited state 23: energy = 0.5000000000086114
Computing excited state 24...
Excited state 24: energy = 1.500000000000016
Computing excited state 25...
Excited state 25: energy = 1.5000000000000167
Computing excited state 26...
Excited state 26: energy = 0.5000000049176908
Computing excited state 27...
Excited state 27: energy = 0.5000000000035039
Computing excited state 28...
Excited state 28: energy = 12.5
Computing excited state 29...
Excited state 29: energy = 1.5
Computing excited state 30...
Excited state 30: energy = 1.500000000000034
Computing excited state 31...
Excited state 31: energy = 13.500000000000009
Computing excited state 32...
Excited state 32: energy = 1.5
Computing excited state 33...
Excited state 33: energy = 13.5
Computing excited state 34...
Excited state 34: energy = 13.499999999999993
Computing excited state 35...
Excited state 35: energy = 2.500000000000007
Computing excited state 36...
Excited state 36: energy = 13.499999999999996
Computing excited state 37...
Excited state 37: energy = 13.50000000000001
Computing excited state 38...
Excited state 38: energy = 14.500000000000004
Computing excited state 39...
Excited state 39: energy = 14.499993461103283
Computing excited state 40...
Excited state 40: energy = 14.500000175820166
```

Once again, the number of states of each energy is correct. If you check through all of these states, you will see 1 state of energy -2.5, 5 states of energy -1.5, 10 states of energy -0.5, 10 states of energy 0.5, 5 states of energy 1.5, and 1 state of energy 2.5, as expected. In addition, since there are only 2^N states but I have deliberately set excite_num > 2^N - 1, we should see the algorithm return to the original low-lying states but now with their energies increased by proj_weight. Indeed we see this--for instance, the original ground state of energy -2.5 will now have energy 12.5, and it shows up as excited state 28. However, it should show up as excited state 32, since it should not be the ground state again until the other 31 states have all been bumped up. Moreover, we see that the highest excited state of energy 2.5 shows up later than it should, as excited state 35 instead of excited state 31. In general, it is clear that the excited states aren't showing up in quite the order that they should.

I'm not sure what could be causing this. This system is highly degenerate due to its simplicity and thus might be weird in ways uncharacteristic of more complicated systems, but I don't think this alone should cause this problem. Any help on this would be greatly appreciated.

**Comment by emstoudenmire** [comment] 2020-04-21 20:14
Hi Sujay,
Yes, this is a very common behavior that we've seen in the past with this approach (in the C++ version, but I don't think it's even that specific to ITensor). I think it's just a fundamental aspect of this way of finding excited states, namely by optimizing while penalizing orthogonality to previous states.

What happens is a complicated, model-dependent interplay between these things:

1. the energy / optimization landscape of the particular Hamiltonian including denegeracies
2. the choice of initial-state MPS used to initialize each DMRG run
3. the value of the weight parameter chosen, relative to the energy scales of the Hamiltonian

Of course items 2 and 3 above are the ones most under the control of the user, but how to choose the initial states and the weight parameter are far from obvious, and something of an open research topic.

Hope that helps - happy to discuss more.

**Comment by emstoudenmire** [comment] 2020-04-21 20:41
I should add that another important consideration is:

4. the number of sweeps you do in DMRG. Five sweeps can be good enough for getting a ground state of a relatively simple Hamiltonian to good accuracy. However, in my experience, excited states can require many more sweeps to converge, such as 20 sweeps. The reason is that excited states often have some kind of local particle-like excitations in them which have to spread out spatially to lower their energy, and it can take a while for DMRG to optimize this. Also I've found that it can help overall to make sure lower-lying states are computed very accurately in order to later get higher-lying excited states.

There are some more advanced things you should consider too:

- are some of the excited states you're after distinguished from each other by a conserved quantity or quantum number? If so, a far superior approach would be to do DMRG calculations in each quantum number sector, where the "ground states" of other sectors besides the one containing the true ground state are actually excited states
- if you want to get really sophisticated, after finding a certain number of approximate excited state MPS, you could compute a matrix of their inner products with each other, then symmetrically orthogonalize this matrix (through an eigenvalue decomposition O = UDU^\dagger) the use the resulting U and D matrices to orthogonalize the excited state MPS in a numerically exact way (up to errors involved when summing MPS). Then you could recompute their energies to get more accurate energies. We don't have a code for this so you'd have to develop it mostly yourself.

**Comment by emstoudenmire** [comment] 2020-04-21 20:43
My comments were overall very general on purpose. Of course the Hamiltonian you're looking at in that code is very simple and certainly has some unusual properties, as you know.

**Comment by emstoudenmire** [comment] 2020-04-23 19:05
Going to go ahead and close this, as it's the expected behavior of this code. But please let me know if you have a support type of question about it.

**Closed by emstoudenmire** 2020-04-23 19:05 UTC

**Comment by sujay-kazi** [comment] 2020-04-23 19:10
No problem. Thank you so much for all of the help!
